public class Calculaation1 {
    public Integer Num1{get;set;}
    public Integer Num2{get;set;}
    public Integer output{get;set;}
    
    public void doAdd(){
        output=Num1 + Num2; 
        
    }
     public void doSub(){
        output=Num1 - Num2; 
        
    }
     public void doMul(){
        output=Num1 * Num2; 
        
    }
     public void doDivi(){
        output=Num1 / Num2; 
        
    }

}